### ISSUE TITLE
連番で読み込んでいる部分について

### ISSUE THREAD

**Issue by yumetodo** [S-H-GAMELINKS/Novel.Game.Engine.LINKS#1]
```cpp
	CHARACTER_LOAD[9] = LoadGraph("DATA/CHARACTER/CHAR10.png");
	CHARACTER_LOAD[10] = LoadGraph("DATA/CHARACTER/CHAR11.png");
	CHARACTER_LOAD[12] = LoadGraph("DATA/CHARACTER/CHAR12.png");
	CHARACTER_LOAD[13] = LoadGraph("DATA/CHARACTER/CHAR13.png");
```

のように配列番号が飛んでいるものが多数見受けられますが、これは意図した挙動でしょうか？

例えば `CHARACTER_LOAD` の場合要素数が100なので0-99までありますが、`CHARxx.pmg` は00-99まであるのか、01-100まであるのか、はたまた01-99(配列の11要素目は空！！)なのかどちらでしょうか？

**Comment by S-H-GAMELINKS** [comment]
配列の11要素目は、単純にこちらのミスで飛んでしまっているようです。

各種素材は01-99まであります。

**Comment by yumetodo** [comment]
すると配列の要素数は99ということですね？

**Comment by S-H-GAMELINKS** [comment]
そうなりますね。

おそらく、文字列配列の話と勘違いしたままでいたようです

お手数おかけします

**Comment by yumetodo** [comment]
#2 のhttps://github.com/yumetodo/Novel.Game.Engine.LINKS/commit/c6fdfc1614ce1af7b15e9ea9b2324828971b673f
でfixできたと思うのでcloseします
