### ISSUE TITLE
セーブデータ一覧画面でのキー操作

### ISSUE THREAD

**Issue by S-H-GAMELINKS** [S-H-GAMELINKS/Novel.Game.Engine.LINKS#18]
セーブデータ一覧画面(セーブ・ロード・データ削除)にて、上下キー操作で各種データを選択しようとしました。

しかし、セーブデータ１とセーブデータ３との間でしかカーソルが動かない模様です。

おそらく、下記の

`SAVE_y = (SAVE_y == (save_buttom_y)) ? save_base_pos_y : SAVE_y + save_move_unit;`

と

`SAVE_y = (save_base_pos_y == SAVE_y) ? save_buttom_y : SAVE_y - save_move_unit;`

の式の評価が絡んでいるのでは？と思います。

```
	//セーブ画面(キー操作)

	void SAVEDATA_KEY_MOVE() {



		if (Key[KEY_INPUT_DOWN] == 1) {

			SAVE_y = (SAVE_y == (save_buttom_y)) ? save_base_pos_y : SAVE_y + save_move_unit;

		}



		if (Key[KEY_INPUT_UP] == 1) {

			SAVE_y = (save_base_pos_y == SAVE_y) ? save_buttom_y : SAVE_y - save_move_unit;

		}

	}
```

引き続き、ソースを調べてみます。

**Comment by yumetodo** [comment]
そうではなくて、`SAVEDATA_KEY_MOVE`が2回呼ばれているようです。なんでだ・・・

**Comment by S-H-GAMELINKS** [comment]
あー、カーソルキー関連でしたか……

**Comment by S-H-GAMELINKS** [comment]
とりあえず、今回のPRで修正されたと思いますので。

このIssueはcloseさせていただきますね。
