### ISSUE TITLE
update fmtlib/fmt

### ISSUE THREAD

**Issue by yumetodo** [S-H-GAMELINKS/Novel.Game.Engine.LINKS#22]
update fmtlib/fmt: 3.0.1 to 3.0.2

https://github.com/fmtlib/fmt/releases/tag/3.0.2

**Comment by S-H-GAMELINKS** [comment]
こちらのほうでアップデートしておきますねー

**Comment by S-H-GAMELINKS** [comment]
とりあえず、手元のソースで使用する`fmtlib/fmt`を3.0.2へと変更しておきました。

**Comment by yumetodo** [comment]
上がってないようです。`.gitmodules`ではなく`fmt`そのものが変更になるはずです。

コマンドがウル覚えですが

```sh
cd fmt
git fetch
git checkout 3.0.2
cd ..
git add fmt
git commit
```

でいけたと思います

**Comment by S-H-GAMELINKS** [comment]
これで、一応いけたと思います。

https://github.com/S-H-GAMELINKS/Novel.Game.Engine.LINKS/commit/a2f1eb85872d4bc918e62d3adbb557e070669785

**Comment by yumetodo** [comment]
ぎゃーーーーーーーーーーーーーーーーーーーーーーー

```sh
git reset HEAD~1 --hard
git push --force
```

して歴史改変せねば！(submodule消えてる！馬鹿でかいdirectory追加された！これはアカン！)

**Comment by S-H-GAMELINKS** [comment]
申し訳ないです……

とりあえず、

```
git reset HEAD~1 --hard
git push --force
```

で、歴史改変しておきました

**Comment by yumetodo** [comment]
https://github.com/S-H-GAMELINKS/Novel.Game.Engine.LINKS/commit/a2f1eb85872d4bc918e62d3adbb557e070669785
だけかと思ったら
https://github.com/S-H-GAMELINKS/Novel.Game.Engine.LINKS/commit/39c9271560c767939b55ccd7bdf014cf0944a8fe
もだったので、再度同じコマンドを実行してください・・・

**Comment by S-H-GAMELINKS** [comment]
https://github.com/S-H-GAMELINKS/Novel.Game.Engine.LINKS/commit/39c9271560c767939b55ccd7bdf014cf0944a8fe

こちらも歴史改変しておきました。
本当に申し訳ない……

**Comment by S-H-GAMELINKS** [comment]
また、`sub module`　消えてる……

また改変しておきますね……

**Comment by S-H-GAMELINKS** [comment]
とりあえず、これでOKでないかと……

https://github.com/S-H-GAMELINKS/Novel.Game.Engine.LINKS/commit/27c0a089477f8ace8a4c106d04a174d26e56b408

**Comment by yumetodo** [comment]
3.0.2にするとhashは https://github.com/fmtlib/fmt/commit/5708bf8fcc1bc2f26b73335dae49a601ecb8882d になると思うんですが・・・

**Comment by yumetodo** [comment]
@S-H-GAMELINKS 確認しました
