### ISSUE TITLE
[proposal] define WIN32_LEAN_AND_MEAN

### ISSUE THREAD

**Issue by yumetodo** [S-H-GAMELINKS/Novel.Game.Engine.LINKS#23]
https://github.com/fmtlib/fmt/pull/503

そういえば `WIN32_LEAN_AND_MEAN`なんていう~~ヘッダ~~マクロがあった。`DxLib.h`に対しても使えるとの情報があるので、コンパイル時間短縮のために使ってみてもいいかもしれない。

[本の虫: oldnewthing: WIN32_LEAN_AND_MEANの由来](https://cpplover.blogspot.jp/2009/12/oldnewthing-win32leanandmean.html)

**Comment by S-H-GAMELINKS** [comment]
知らなかったです。`WIN32_LEAN_AND_MEAN`というヘッダがあるんですか……

ちょっと手元のソースで確認してみますね。

**Comment by yumetodo** [comment]
マクロだった。

**Comment by S-H-GAMELINKS** [comment]
手元のソースで確認してみたところ、1秒程度コンパイル時間が短縮できた模様です(ソリューションのリビルドで計測)。

とりあえず、一回commitしておきますね

**Comment by yumetodo** [comment]
ええっと `#include <DxLib.h>` および `#include <Windows.h>`している箇所はもっとあったと思うのですが・・・

**Comment by S-H-GAMELINKS** [comment]
申し訳ありません。

うっかり、しておりました……。

とりあえず、先ほどのcommitで追記してきました。

**Comment by yumetodo** [comment]
コンパイルしてないですが、二重define大丈夫ですかね・・・

**Comment by S-H-GAMELINKS** [comment]
とりあえず、コードの分析を走らせてみたんですが、問題なさそうです……

**Comment by S-H-GAMELINKS** [comment]
一応、問題ないようですのでcloseしようかと思います。
closeしてもよろしいでしょうか？

**Comment by yumetodo** [comment]
closeします
