### ISSUE TITLE
スクリプト配列：String の動的確保について

### ISSUE THREAD

**Issue by S-H-GAMELINKS** [S-H-GAMELINKS/Novel.Game.Engine.LINKS#25]
こちらのスクリプト配列：String を

```
//スクリプト用読込配列
char String[script_line_num_lim][script_line_string_len_lim];
```

下記のコードで行数と文字数(バイト数)を返して、配列を動的確保できないでしょうか？

```
//行数カウント関数
int CountLine(){

    //カウンタ変数
    int number = 0;

    //テキストを開く
    ifstream file("sample.txt");

    //テキストの行数をカウント
    while(!file.eof()){
        string s;
        getline(file, s);
        number++;
    }

    return number;
}

//文字数カウント関数(バイト数)
int CountWord(){

    //各種カウンタ変数の初期化
    int number = 0;
    int word1 = 0;
    int word2 = 0;

    //テキストを開く
    ifstream file("sample.txt");

    //一行ずつ文字数をカウントし、最大値を返す
    while(!file.eof()){
        string s;
        getline(file, s);
        word2 = word1;
        word1 = s.length();
        if(number <= word1 || word2 >= number)
            number = max(word1, word2);
        //number = max(word2, number);
    }

    return number;
}
```

**Comment by yumetodo** [comment]
現状`FileRead_gets`で読み込みをしていますが、この場合DXArchiveに対応しています。この対応を切ってもいいなら比較的ラクにできますが、DXA対応が必要な場合はFileRead周りをラップすることになり大変です。どうしますか？

いずれにしても動的確保にすることでメモリー使用量削減に寄与するかと思います。

**Comment by S-H-GAMELINKS** [comment]
あー、DXArchive周りの事まで考えが回ってなかったですね…。

DXArchive非対応となるのはユーザーからすると辛いでしょうし、かといってラップするというのも大変ですし。

**Comment by yumetodo** [comment]
やっぱり対応しないとあかんか・・・。結局
https://github.com/Nagarei/DxLibEx/pull/53#issuecomment-218428288
と同じ問題にぶち当たるのか・・・。

まあようは`std::streambuf`, `std::istream`, `std::ostream`をそれぞれ継承してやればいいんだけど、本当に設計が古臭くてだるい。

**Comment by S-H-GAMELINKS** [comment]
個人的には、DXA対応を切ってしまっても問題ないと思いますよ。

それに、現状ユーザーからの声はほとんどないですので(サークルメンバーからのみ……)、DXA非対応になったとしても大きな問題にはならないと考えます。

この際ですし、非対応の方向で行きましょうか。

**Comment by yumetodo** [comment]
ちなみに前に`std::wcin`/ `std::wcout`をUTF-8としてバイパスする目的で書いたstreambufが
https://github.com/yumetodo/utf8_streambuf
です。まあこれよりは楽に書けるんじゃないかな・・・

非対応だと嬉しいです。

---

以下愚痴。

<details>
そもそもDXAって話を複雑にしているだけで不要だと思うんですよね。画像、動画、音声はzlib圧縮ごときではさして縮まないどころか下手すると増えますし。唯一価値があるのはテキストファイルですが、これだってファイル単位で<code>boost::iostreams</code>とかでzlibなりbzip2で圧縮すればいいんですよ。たまにDXAの暗号化が必要だからとか言っている輩がいますが、解除鍵がプログラム中にある時点でいくらでも逆アセンブルして割れますし、ネットワーク通信で手に入れる実装にしても通信がある事自体はオフライン環境で実行すればわかるし、通信内容はWireSharkでわかるし、結局無意味なんですよ。もちろんDRMの認証に使っているものくらい頑張ればそうそう破られないでしょうが、そんなコードかけるやつはDXAなんてつかいませんよ。そんなにリソースファイル隠したいならもうブラウザゲームにしろよっていう・・・。改ざん対策にDXA使うのも誤りで、そんなもんハッシュチェックしろよと申し上げたい。つまりDXAなんてゴミ箱に投げ捨てるべきなんですよ。ええ、あんなものがあるせいで<code>boost::iostreams</code>をstatic linkしようとするとリンカーエラーになるし、まじでDXA考えたやつは頭が(ry
</details>

(DXAへの恨みのあまり錯乱したので隠しました)

**Comment by S-H-GAMELINKS** [comment]
よし、非対応にしましょう！

個人的にも、DXAでの暗号化は「見ようと思えばみれてしまうよな」という思いがありましたので、今回の件はいい区切りだと思います。

あと、それ以上いけない……

**Comment by yumetodo** [comment]
了解です。試しに実装してみています・・・

**Comment by S-H-GAMELINKS** [comment]
よろしくお願いします。m(__)m

**Comment by S-H-GAMELINKS** [comment]
#27 のPull request にて動的確保が実装できていますので、この issue は close しますね。
