### ISSUE TITLE
タイトルへ戻った後、ロード画面が呼び出せない

### ISSUE THREAD

**Issue by S-H-GAMELINKS** [S-H-GAMELINKS/Novel.Game.Engine.LINKS#30]
ゲームメニューよりタイトルへ戻った際に、セーブデータのロード画面が開けない現象が確認できました。

タイトルに戻る際に GAMEMENU_COUNT に true が渡され、それがそのままになっているようです。

こちらで、修正しておきましょうか？

**Comment by yumetodo** [comment]
お願いします。

TODO: しかし根本解決のためにはあの画面変遷周りのフラグをどうにかしなければ・・・

**Comment by S-H-GAMELINKS** [comment]
了解しました。こちらで修正しておきますねー。

確かに、画面変遷周りのフラグが……

**Comment by S-H-GAMELINKS** [comment]
修正しておきましたー。

一応、実際に動作させて確認も取れていますので大丈夫だと思います
