### ISSUE TITLE
動画以外の素材が利用できない

### ISSUE THREAD

**Issue by yumetodo** [S-H-GAMELINKS/Novel.Game.Engine.LINKS#5]
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">ビルドしてみたが、立ち絵他描画できてないっぽい。<br><br>んー、タグに反応してるみたいだが…</p>&mdash; ゲームリンクス (@GAME_LINKS_) <a href="https://twitter.com/GAME_LINKS_/status/868838350161039362">2017年5月28日</a></blockquote>
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">ログにエラー出てないなぁ。<br><br>って事は、ファイルそのものを開きにいってないんかな？</p>&mdash; ゲームリンクス (@GAME_LINKS_) <a href="https://twitter.com/GAME_LINKS_/status/868845919726256130">2017年5月28日</a></blockquote>
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">いや、C99タグまで登録した時に開けなかったらファイルは全てエラーで出てたな。</p>&mdash; ゲームリンクス (@GAME_LINKS_) <a href="https://twitter.com/GAME_LINKS_/status/868846605495128064">2017年5月28日</a></blockquote>
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">という事は、それ以前の段階の話か</p>&mdash; ゲームリンクス (@GAME_LINKS_) <a href="https://twitter.com/GAME_LINKS_/status/868846767659298816">2017年5月28日</a></blockquote>
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">ソース見る感じでは、随時タグに合わせてロードしてる？<br><br>となると、以前までの一括ロードとは違うからエラーは出てこないよな</p>&mdash; ゲームリンクス (@GAME_LINKS_) <a href="https://twitter.com/GAME_LINKS_/status/868997817334759424">2017年5月29日</a></blockquote>
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">動画は再生されてる模様。<br>動画以外の素材は軒並みダメみたいかなー？</p>&mdash; ゲームリンクス (@GAME_LINKS_) <a href="https://twitter.com/GAME_LINKS_/status/869034543503646720">2017年5月29日</a></blockquote>

**Comment by yumetodo** [comment]
>ソース見る感じでは、随時タグに合わせてロードしてる？

そんなことはない(動画除く)

**Comment by yumetodo** [comment]
@S-H-GAMELINKS テストファイルいただけたりしないですかね・・・？

それはそうとサウンド系もだめですか？(立ち絵、背景画像、ＢＧＭ、ＳＥでロジック共通だからだめなはず)

**Comment by S-H-GAMELINKS** [comment]
配布しているものになりますが、こちらで一応のテストが可能です。

http://ux.getuploader.com/GAMELINKS001/download/56/LINKS.zip

やはり、サウンド系も駄目のようです。現状、逐次ロードしている動画素材のみ描画できていますね。
