### ISSUE TITLE
[proposal]fmtlib/fmtの導入

### ISSUE THREAD

**Issue by yumetodo** [S-H-GAMELINKS/Novel.Game.Engine.LINKS#8]
#5 のバグは文字列操作に起因するものだった。
文字列操作はCでやるべきではなく、かと言ってC++標準ライブラリは

```cpp
std::cout << std::setprecision(2) << std::fixed << 1.23456 << "\n";
```

設計が古く(可変長templateがない時代)冗長である。

```cpp
fmt::print("Hello, {}!", "world");  // uses Python-like format string syntax
fmt::printf("Hello, %s!", "world"); // uses printf format string syntax
```

のように安全で見た目もスッキリし、動作が高速なfmtlib/fmtを利用することを提案する。

`FMT_HEADER_ONLY` macroを定義することでヘッダーオンリーで利用できる

https://github.com/fmtlib/fmt

**Comment by S-H-GAMELINKS** [comment]
Cで文字列操作を行うべきでないことは、先ほどの#5で知りましたし、

見た目もすっきりする上に、動作が高速であるならば、それを活用しない手はありませんね。

**Comment by yumetodo** [comment]
#12 で導入したのでcloseする
